eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9001
spring:
  application:
    name: eurekaClientA
rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: testProducerGroup
    #mq的nameserver地址
    namesrvAddr: 47.93.193.177:9876
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: testProducer
    #topic名称
    topic: test
    #根据实际情况设置消息的tag
    tag: test
    #消息最大长度
    #1024*128
    maxMessageSize: 131072 
    #发送消息超时时间
    sendMsgTimeout: 10000
  consumer:
    namesrvAddr: 47.93.193.177:9876
    groupName: testConsumerGroup
    topic: test
    tag: test
    consumeThreadMin: 20
    consumeThreadMax: 64